name: CI - Vérifications de code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-syntax-check:
    name: Vérification syntaxe Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Vérification de la syntaxe Python
        run: |
          python -m py_compile src/api/main.py
          python -m py_compile src/ingestion/loader.py
          python -m py_compile src/rag/rag_chain.py
          python -m py_compile src/database/session.py
          python -m py_compile src/database/crud.py
          python -m py_compile src/classification/classifier.py

      - name: Vérification syntaxe YAML des manifestes K8s
        run: |
          pip install pyyaml
          python -c "
          import yaml, glob
          for f in glob.glob('k8s/*.yaml'):
              with open(f) as file:
                  list(yaml.safe_load_all(file))
              print(f'{f}: OK')
          "

  build-and-push:
    name: Build et publication des images Docker
    runs-on: ubuntu-latest
    needs: lint-and-syntax-check   # n'exécute ce job QUE si le précédent a réussi
    if: github.ref == 'refs/heads/main'   # uniquement sur la branche main, pas sur les PR

    permissions:
      contents: read
      packages: write   # nécessaire pour pouvoir pousser vers ghcr.io

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et push de l'image API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mlops-platform-api:latest

      - name: Build et push de l'image Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mlops-platform-frontend:latest
          build-args: |
            VITE_API_BASE_URL=http://localhost:8000